release how-to
fractal-analytics-platform/fractal pull request #200
Opened 2022-09-08 12:46 UTC by jacopo-exact

ref #192

2022-09-08 14:43 UTC, tcompa commented
Should we also update `__VERSION__` in `fractal/client/config.py` by hand?

2022-09-08 14:44 UTC, tcompa requested changes
Should we also update __VERSION__ in fractal/client/config.py by hand?

2022-09-08 15:15 UTC, jacopo-exact commented
> Should we also update **VERSION** in fractal/client/config.py by hand?

we have redundant VERSIONs around. I will rationalise them and leave only one coded version that gets automatically updated.

from pyproject.toml you can see how `bumpver` is able to find and replace occurrences of the version tag, if correctly instructed to do so.

2022-09-12 12:19 UTC, tcompa approved these changes

2022-09-12 12:19 UTC, merged